#!/usr/bin/env python
# coding: utf-8

# # Limitations of GDP

# - GDP fails to account for nonmarket transactions.<br>GDP understates the value generated by an economy by 50%.
# - GDP fails to account for inflation.<br>If the prices of goods and services increases but the production is the same, GDP will also increase.
# - Cannot be used as an indicator of standards of living.
#     - Greater population, greater GDP but low GDP per capita (China and Japan).

# ```{note}
# Real GDP
# : GDP given in constant prices.
# : Inflation is deducted.<br><br>
# 
# Real GDP per capita
# : Real GDP per person.
# : **Always choose this one.**
# ```
